spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

server:
  port: 8101

mybatis:
  config-location: classpath:mybatis-config.xml

---
spring:
  profiles: local
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/userDB?useSSL=false&allowPublicKeyRetrieval=true
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: trace
  org.springframework: DEBUG
  org.apache.coyote: INFO
  mybatis.sql: trace


logging:
  config: classpath:logback/logback-spring.xml


tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8200
    enabled: true


